import os


AWS_REGION=os.environ['AWS_REGION']
AWS_COGNITO_USER_POOL_ID=os.environ['AWS_COGNITO_USER_POOL_ID']
SECRET_KEY=os.environ['SECRET_KEY']
AWS_COGNITO_DOMAIN=os.environ['AWS_COGNITO_DOMAIN']
AWS_COGNITO_USER_POOL_CLIENT_ID=os.environ['AWS_COGNITO_USER_POOL_CLIENT_ID']
AWS_COGNITO_REDIRECT_URL=os.environ['AWS_COGNITO_REDIRECT_URL']
AWS_COGNITO_LOGOUT_URL=os.environ['AWS_COGNITO_LOGOUT_URL']



