name: Push to dockerhub

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag redthorx/mse-chat-login-service:$(date +%s) --tag redthorx/mse-chat-login-service:latest
      
      - name: Push Docker image
        run: docker push redthorx/mse-chat-login-service
